#[cfg(feature = "mkl")]
extern crate intel_mkl_src;

#[cfg(feature = "accelerate")]
extern crate accelerate_src;

use clap::{Parser, ValueEnum};
use std::io::Write;
use tokenizers::Tokenizer;

use candle::Tensor;
use candle::{quantized::gguf_file, DType};
use candle_transformers::generation::{LogitsProcessor, Sampling};

use candle_examples::token_output_stream::TokenOutputStream;
use candle_transformers::models::quantized_qwen3_moe::GGUFQWenMoE as Qwen3_MoE;

const DEFAULT_PROMPT: &str = "Write a Rust function to calculate the factorial of a given number.";

#[derive(Clone, Debug, Copy, PartialEq, Eq, ValueEnum)]
enum Which {
    #[value(name = "16b_q2k")]
    W3_16bQ2K,
    #[value(name = "16b_q4k")]
    W3_16bQ4K,
    #[value(name = "16b_q6k")]
    W3_16bQ6K,
    #[value(name = "16b_q80")]
    W3_16bQ80,
    #[value(name = "32b_q2k")]
    W3_32bQ2K,
    #[value(name = "32b_q4k")]
    W3_32bQ4K,
    #[value(name = "32b_q6k")]
    W3_32bQ6K,
    #[value(name = "32b_q80")]
    W3_32bQ80,
}

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// GGUF file to load, typically a .gguf file generated by the quantize command from llama.cpp
    #[arg(long)]
    model: Option<String>,

    /// The initial prompt, use 'interactive' for entering multiple prompts in an interactive way
    /// and 'chat' for an interactive model where history of previous prompts and generated tokens
    /// is preserved.
    #[arg(long)]
    prompt: Option<String>,

    /// The length of the sample to generate (in tokens).
    #[arg(short = 'n', long, default_value_t = 1000)]
    sample_len: usize,

    /// The tokenizer config in json format.
    #[arg(long)]
    tokenizer: Option<String>,

    /// The temperature used to generate samples, use 0 for greedy sampling.
    #[arg(long, default_value_t = 0.8)]
    temperature: f64,

    /// Nucleus sampling probability cutoff.
    #[arg(long)]
    top_p: Option<f64>,

    /// Only sample among the top K samples.
    #[arg(long)]
    top_k: Option<usize>,

    /// The seed to use when generating random samples.
    #[arg(long, default_value_t = 299792458)]
    seed: u64,

    /// Enable tracing (generates a trace-timestamp.json file).
    #[arg(long)]
    tracing: bool,

    /// Process prompt elements separately.
    #[arg(long)]
    split_prompt: bool,

    /// Run on CPU rather than GPU even if a GPU is available.
    #[arg(long)]
    cpu: bool,

    /// Penalty to be applied for repeating tokens, 1. means no penalty.
    #[arg(long, default_value_t = 1.1)]
    repeat_penalty: f32,

    /// The context size to consider for the repeat penalty.
    #[arg(long, default_value_t = 64)]
    repeat_last_n: usize,

    /// The model size to use.
    #[arg(long, default_value = "16b_q2k")]
    which: Which,

    #[arg(long, default_value = "bf16")]
    dtype: String,

    /// Capture the decode step into a CUDA/HIP graph and replay it per token.
    /// GPU-only; ignores itself on CPU runs with a warning.
    #[arg(long)]
    graph: bool,

    /// Maximum sequence length the graph decode path supports (defaults to
    /// prompt + sample length + 32).
    #[arg(long)]
    max_seq: Option<usize>,
}

impl Args {
    fn tokenizer(&self) -> anyhow::Result<Tokenizer> {
        let tokenizer_path = match &self.tokenizer {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let api = candle_examples::hub::Api::new()?;
                let repo = "Qwen/Qwen3-30B-A3B-Instruct-2507";
                let api = api.model(repo);
                api.get("tokenizer.json")?
            }
        };
        Tokenizer::from_file(tokenizer_path).map_err(anyhow::Error::msg)
    }

    fn model(&self) -> anyhow::Result<std::path::PathBuf> {
        let model_path = match &self.model {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let (repo, filename, revision) = match self.which {
                    Which::W3_16bQ2K => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q2_K.gguf",
                        "main",
                    ),
                    Which::W3_16bQ4K => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q4_K_M.gguf",
                        "main",
                    ),
                    Which::W3_16bQ6K => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q6_K.gguf",
                        "main",
                    ),
                    Which::W3_16bQ80 => (
                        "unsloth/Qwen3-16B-A3B-GGUF",
                        "Qwen3-16B-A3B-Q8_0.gguf",
                        "main",
                    ),

                    Which::W3_32bQ2K => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q2_K.gguf",
                        "main",
                    ),
                    Which::W3_32bQ4K => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf",
                        "main",
                    ),
                    Which::W3_32bQ6K => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q6_K.gguf",
                        "main",
                    ),
                    Which::W3_32bQ80 => (
                        "unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF",
                        "Qwen3-30B-A3B-Instruct-2507-Q8_0.gguf",
                        "main",
                    ),
                };
                let api = candle_examples::hub::Api::new()?;
                api.model(repo).with_revision(revision).get(filename)?
            }
        };
        Ok(model_path)
    }
}

fn format_size(size_in_bytes: usize) -> String {
    if size_in_bytes < 1_000 {
        format!("{size_in_bytes}B")
    } else if size_in_bytes < 1_000_000 {
        format!("{:.2}KB", size_in_bytes as f64 / 1e3)
    } else if size_in_bytes < 1_000_000_000 {
        format!("{:.2}MB", size_in_bytes as f64 / 1e6)
    } else {
        format!("{:.2}GB", size_in_bytes as f64 / 1e9)
    }
}

/// Overwrite the (single) u32 in a CUDA device tensor in place with no new
/// device allocation, so it can be shared with a captured graph.
fn h2d_copy_u32(t: &Tensor, v: u32) -> anyhow::Result<()> {
    use candle::Storage;
    let (s, _l) = t.storage_and_layout();
    match &*s {
        Storage::Cuda(c) => {
            let slice = c.as_cuda_slice::<u32>()?;
            let mut view = unsafe { slice.as_view().as_mut_view() };
            c.device.memcpy_htod(&[v], &mut view)?;
        }
        _ => anyhow::bail!("expected a CUDA tensor for in-place u32 update"),
    }
    Ok(())
}

fn main() -> anyhow::Result<()> {
    use tracing_chrome::ChromeLayerBuilder;
    use tracing_subscriber::prelude::*;

    let args = Args::parse();
    let _guard = if args.tracing {
        let (chrome_layer, guard) = ChromeLayerBuilder::new().build();
        tracing_subscriber::registry().with(chrome_layer).init();
        Some(guard)
    } else {
        None
    };

    println!(
        "avx: {}, neon: {}, simd128: {}, f16c: {}",
        candle::utils::with_avx(),
        candle::utils::with_neon(),
        candle::utils::with_simd128(),
        candle::utils::with_f16c()
    );
    println!(
        "temp: {:.2} repeat-penalty: {:.2} repeat-last-n: {}",
        args.temperature, args.repeat_penalty, args.repeat_last_n
    );

    let dtype = match args.dtype.as_str() {
        "bf16" => DType::BF16,
        "f16" => DType::F16, // Used for V100
        _ => {
            panic!("Not supported dtype!")
        }
    };

    let model_path = args.model()?;
    let mut file = std::fs::File::open(&model_path)?;
    let start = std::time::Instant::now();
    let device = candle_examples::device(args.cpu)?;

    let (mut model, gguf_tokenizer) = {
        let content = gguf_file::Content::read(&mut file).map_err(|e| e.with_path(model_path))?;
        let mut total_size_in_bytes = 0;
        for tensor in content.tensor_infos.values() {
            let elem_count = tensor.shape.elem_count();
            total_size_in_bytes +=
                elem_count * tensor.ggml_dtype.type_size() / tensor.ggml_dtype.block_size();
        }
        println!(
            "loaded {:?} tensors ({}) in {:.2}s",
            content.tensor_infos.len(),
            format_size(total_size_in_bytes),
            start.elapsed().as_secs_f32(),
        );
        // GGUF files embed their tokenizer in the metadata; prefer it so no
        // separate tokenizer.json is required.
        let gguf_tokenizer =
            candle::quantized::tokenizer::TokenizerFromGguf::from_gguf(&content).ok();
        let model = Qwen3_MoE::from_gguf(content, &mut file, &device, dtype)?;
        (model, gguf_tokenizer)
    };
    println!("model built");

    let tokenizer = match (&args.tokenizer, gguf_tokenizer) {
        (Some(_), _) => args.tokenizer()?,
        (None, Some(t)) => {
            println!("using tokenizer embedded in the GGUF");
            t
        }
        (None, None) => args.tokenizer()?,
    };
    let mut tos = TokenOutputStream::new(tokenizer);
    let prompt_str = args
        .prompt
        .clone()
        .unwrap_or_else(|| DEFAULT_PROMPT.to_string());

    let prompt_str = format!("<|im_start|>user\n{prompt_str}<|im_end|>\n<|im_start|>assistant\n");
    print!("formatted prompt: {}", prompt_str);

    let tokens = tos
        .tokenizer()
        .encode(prompt_str, true)
        .map_err(anyhow::Error::msg)?;

    let tokens = tokens.get_ids();

    let to_sample = args.sample_len.saturating_sub(1);

    let mut all_tokens = vec![];

    let mut logits_processor = {
        let temperature = args.temperature;
        let sampling = if temperature <= 0. {
            Sampling::ArgMax
        } else {
            match (args.top_k, args.top_p) {
                (None, None) => Sampling::All { temperature },
                (Some(k), None) => Sampling::TopK { k, temperature },
                (None, Some(p)) => Sampling::TopP { p, temperature },
                (Some(k), Some(p)) => Sampling::TopKThenTopP { k, p, temperature },
            }
        };
        LogitsProcessor::from_sampling(args.seed, sampling)
    };

    let start_prompt_processing = std::time::Instant::now();

    let mut next_token = if !args.split_prompt {
        let input = Tensor::new(tokens, &device)?.unsqueeze(0)?;
        let logits = model.forward(&input, 0)?;
        let logits = logits.squeeze(0)?;
        logits_processor.sample(&logits)?
    } else {
        let mut next_token = 0;
        for (pos, token) in tokens.iter().enumerate() {
            let input = Tensor::new(&[*token], &device)?.unsqueeze(0)?;
            let logits = model.forward(&input, pos)?;
            let logits = logits.squeeze(0)?;
            next_token = logits_processor.sample(&logits)?
        }
        next_token
    };

    let prompt_dt = start_prompt_processing.elapsed();

    all_tokens.push(next_token);

    if let Some(t) = tos.next_token(next_token)? {
        print!("{t}");
        std::io::stdout().flush()?;
    }

    let eos_token = *tos.tokenizer().get_vocab(true).get("<|im_end|>").unwrap();

    let start_post_prompt = std::time::Instant::now();

    let penalty_fn = |logits: &Tensor, all_tokens: &Vec<u32>| -> candle::Result<Tensor> {
        if args.repeat_penalty == 1. {
            Ok(logits.clone())
        } else {
            let start_at = all_tokens.len().saturating_sub(args.repeat_last_n);
            candle_transformers::utils::apply_repeat_penalty(
                logits,
                args.repeat_penalty,
                &all_tokens[start_at..],
            )
        }
    };

    let mut sampled = 0;

    if args.graph {
        let cuda_dev = match device.as_cuda_device() {
            Ok(d) => Some(d),
            Err(_) => {
                eprintln!("warning: --graph ignored, device is not a CUDA device");
                None
            }
        };
        if let Some(cuda_dev) = cuda_dev {
            let max_seq = args.max_seq.unwrap_or(tokens.len() + to_sample + 32);
            let base = tokens.len();
            model.prepare_graph(max_seq)?;

            // Stable input buffers: the embedding gather and every
            // position-dependent op in the graph read from these, so updating
            // them with H2D copies between replays is all that's needed.
            let input = Tensor::new(&[next_token], &device)?.unsqueeze(0)?;
            let pos_idx = Tensor::new(&[base as u32], &device)?;

            let mut pos = base;
            // With the HTOD cache enabled, host parameter vectors (kernel dim
            // & stride tables) are staged into persistent device buffers on
            // first use (warm-up), so the captured graph performs no host->
            // device copies: baking a copy of a temporary host buffer into a
            // graph node dangles when the graph replays.
            let _htod_guard = cuda_dev.enable_cuda_graph_htod_cache();

            // CANDLE_GRAPH_EAGER=1: run the graph-safe forward eagerly (no
            // capture) to isolate graph capture issues.
            if let Ok(v) = std::env::var("CANDLE_GRAPH_EAGER") {
                eprintln!("CANDLE_GRAPH_EAGER={v}: no-capture diagnostic mode");
                for _ in 0..to_sample {
                    let logits = model.forward_graph(&input, &pos_idx)?.squeeze(0)?;
                    let logits = penalty_fn(&logits, &all_tokens)?;
                    let next_token = logits_processor.sample(&logits)?;
                    all_tokens.push(next_token);
                    if let Some(t) = tos.next_token(next_token)? {
                        print!("{t}");
                        std::io::stdout().flush()?;
                    }
                    sampled += 1;
                    if next_token == eos_token {
                        break;
                    }
                    h2d_copy_u32(&input, next_token)?;
                    pos += 1;
                    h2d_copy_u32(&pos_idx, pos as u32)?;
                }
            } else {
                // Eager warm-up step at position `base`: exercises every kernel
                // (JIT loads, BLAS workspaces, graph-safe state) before capture
                // and doubles as the measurement run that sizes the capture
                // arena. Yields the first graph-path token.
                cuda_dev.reset_alloc_counter();
                let logits = model.forward_graph(&input, &pos_idx)?.squeeze(0)?;
                let logits = penalty_fn(&logits, &all_tokens)?;
                let next_token = logits_processor.sample(&logits)?;
                all_tokens.push(next_token);
                if let Some(t) = tos.next_token(next_token)? {
                    print!("{t}");
                    std::io::stdout().flush()?;
                }
                sampled += 1;
                let mut done = next_token == eos_token;

                // Write the next request and capture the decode step.
                if !done {
                    let budget = cuda_dev.alloc_counter();
                    let arena_bytes = budget * 2 + 4 * 1024 * 1024;
                    let arena = cuda_dev.graph_capture_arena(arena_bytes)?;
                    eprintln!("capture arena: {budget} bytes measured, {arena_bytes} reserved");
                    h2d_copy_u32(&input, next_token)?;
                    pos += 1;
                    h2d_copy_u32(&pos_idx, pos as u32)?;
                    cuda_dev.start_graph_capture_arena(&arena)?;
                    let logits = model.forward_graph(&input, &pos_idx)?.squeeze(0)?;
                    let exec = cuda_dev.end_graph_capture()?;
                    eprintln!("captured decode graph ({max_seq} max seq)");
                    // ROCm does not guarantee that work recorded during a
                    // stream capture actually executes while capturing (CUDA
                    // does), so run the captured step once to produce its
                    // logits. The step is idempotent under replay (the KV
                    // scatter overwrites the same row and the mask is rebuilt
                    // from the unchanged position), so a double execution on a
                    // driver that does run capture work is harmless.
                    cuda_dev.replay_graph(&exec)?;

                    let remaining = to_sample.saturating_sub(sampled);
                    for _ in 0..remaining {
                        let logits = penalty_fn(&logits, &all_tokens)?;
                        let next_token = logits_processor.sample(&logits)?;
                        all_tokens.push(next_token);
                        if let Some(t) = tos.next_token(next_token)? {
                            print!("{t}");
                            std::io::stdout().flush()?;
                        }
                        sampled += 1;
                        if next_token == eos_token {
                            break;
                        }
                        if pos + 1 >= max_seq {
                            eprintln!("reached max_seq {max_seq}, stopping");
                            break;
                        }
                        h2d_copy_u32(&input, next_token)?;
                        pos += 1;
                        h2d_copy_u32(&pos_idx, pos as u32)?;
                        cuda_dev.replay_graph(&exec)?;
                    }
                }
            }
        }
    } else {
        for index in 0..to_sample {
            let input = Tensor::new(&[next_token], &device)?.unsqueeze(0)?;
            let logits = model.forward(&input, tokens.len() + index)?;
            let logits = logits.squeeze(0)?;
            let logits = penalty_fn(&logits, &all_tokens)?;
            next_token = logits_processor.sample(&logits)?;
            all_tokens.push(next_token);
            if let Some(t) = tos.next_token(next_token)? {
                print!("{t}");
                std::io::stdout().flush()?;
            }
            sampled += 1;
            if next_token == eos_token {
                break;
            };
        }
    }

    if let Some(rest) = tos.decode_rest().map_err(candle::Error::msg)? {
        print!("{rest}");
    }

    std::io::stdout().flush()?;
    let dt = start_post_prompt.elapsed();
    println!(
        "\n\n{:4} prompt tokens processed: {:.2} token/s",
        tokens.len(),
        tokens.len() as f64 / prompt_dt.as_secs_f64(),
    );
    println!(
        "{sampled:4} tokens generated: {:.2} token/s",
        sampled as f64 / dt.as_secs_f64(),
    );
    Ok(())
}
